INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('07','BANCOLOMBIA S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('09','CITIBANK COLOMBIA', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('10','BANCO GNB COLOMBIA S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('12','BANCO GNB SUDAMERIS COLOMBIA', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('13','BBVA COLOMBIA', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('14','HELM BANK', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('19','RED MULTIBANCA COLPATRIA S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('23','BANCO DE OCCIDENTE', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('31','BANCO DE COMERCIO EXTERIOR DE COLOMBIA S.A. (BANCOLDEX)', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('32','BANCO CAJA SOCIAL - BCSC S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('40','BANCO AGRARIO DE COLOMBIA S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('51','BANCO DAVIVIENDA S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('52','BANCO AV VILLAS', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('53','BANCO WWB S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('58','BANCO PROCREDIT', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('59','BANCAMIA', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('60','BANCO PICHINCHA S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('61','BANCOOMEVA', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('62','BANCO FALABELLA S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('63','BANCO FINANDINA S.A.', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('65','BANCO SANTANDER DE NEGOCIOS COLOMBIA S.A. - BANCO SANTANDER', false);
INSERT INTO recursos_h_banco(codigo, nombre, eliminado) VALUES ('66','BANCO COOPERATIVO COOPCENTRAL', false);