INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (2,'BANCO DE BOGOTÁ','01',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (3,'BANCO POPULAR','02',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (4,'BANCO CORPBANCA COLOMBIA S.A.','06',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (5,'BANCOLOMBIA S.A.','07',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (6,'CITIBANK COLOMBIA','09',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (7,'BANCO GNB COLOMBIA S.A.','10',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (8,'BANCO GNB SUDAMERIS COLOMBIA','12',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (9,'BBVA COLOMBIA','13',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (10,'HELM BANK','14',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (11,'RED MULTIBANCA COLPATRIA S.A.','19',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (12,'BANCO DE OCCIDENTE','23',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (13,'BANCO DE COMERCIO EXTERIOR DE COLOMBIA S.A. (BANCOLDEX)','31',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (14,'BANCO CAJA SOCIAL - BCSC S.A.','32',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (15,'BANCO AGRARIO DE COLOMBIA S.A.','40',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (16,'BANCO DAVIVIENDA S.A.','51',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (17,'BANCO AV VILLAS','52',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (18,'BANCO WWB S.A.','53',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (19,'BANCO PROCREDIT','58',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (20,'BANCAMIA','59',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (21,'BANCO PICHINCHA S.A.','60',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (22,'BANCOOMEVA','61',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (23,'BANCO FALABELLA S.A.','62',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (24,'BANCO FINANDINA S.A.','63',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (25,'BANCO SANTANDER DE NEGOCIOS COLOMBIA S.A. - BANCO SANTANDER','65',FALSE);
INSERT INTO recursos_h_banco(id, nombre, codigo, eliminado) VALUES (26,'BANCO COOPERATIVO COOPCENTRAL','66',FALSE);
