# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 22:43
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_banco', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_banco', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_banco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='CajaCompensacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_caja', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_caja', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja de compensaci\xf3n',
                'verbose_name_plural': 'Cajas de compencaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cargo', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_cargo', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_cargo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cesantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cesantia', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_cesantia', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_cesantia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cesant\xeda',
                'verbose_name_plural': 'Cesant\xedas',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario base legal')),
                ('subsidio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subsidio de transporte')),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('descanso_turno', models.BooleanField(verbose_name='Descanso entre turnos')),
                ('inicio_descanso', models.IntegerField(blank=True, null=True, verbose_name='Hora de inicio de descanso')),
                ('duracion_descanso', models.IntegerField(blank=True, null=True, verbose_name='Duraci\xf3n de descanso en minutos')),
                ('horas_trabajo', models.IntegerField(default=8, verbose_name='Horas de trabajo diarias')),
                ('horas_trabajo_semanal', models.IntegerField(default=40, verbose_name='Horas de trabajo semanal')),
                ('horas_trabajo_corte', models.IntegerField(default=160, verbose_name='Horas de trabajo mes')),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_contrato', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_contrato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=100, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=100, verbose_name='Numero de cuenta')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Banco')),
                ('cajacompensacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.CajaCompensacion')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Cargo')),
                ('cesantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Cesantia')),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_eps', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_eps', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_eps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eps',
                'verbose_name_plural': 'Eps',
            },
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_pension', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_pension', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_pension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pensi\xf3n',
                'verbose_name_plural': 'Pensiones',
            },
        ),
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eliminado', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Cargo')),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tarifario', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_tarifario', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_tarifario', to=settings.AUTH_USER_MODEL)),
                ('remplazado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Tarifario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modalidad', models.IntegerField(choices=[(1, 'Por hora'), (2, 'Salario fijo'), (3, 'Producci\xf3n')])),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tipo_contrato', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_tipo_contrato', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_tipo_contrato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de contrato',
                'verbose_name_plural': 'Tipos de contrato',
            },
        ),
        migrations.CreateModel(
            name='UnidadProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_unidad', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_unidad', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_unidad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tarifario',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.UnidadProduccion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Eps'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleado',
            name='pension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Pension'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Empleado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_contrato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.TipoContrato'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='unidades_produccion',
            field=models.ManyToManyField(to='recursos_h.UnidadProduccion'),
        ),
    ]
