# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 03:41
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_h', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_banco', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_banco', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_banco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Banco')),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_cuenta', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_cuenta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_unidad', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_unidad', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_unidad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='valor_hora_diurna',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='valor_hora_festivo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='valor_hora_nocturna',
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario base legal'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='subsidio_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subsidio de transporte'),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='modalidad',
            field=models.IntegerField(choices=[(1, 'Por hora'), (2, 'Salario fijo'), (3, 'Producci\xf3n')]),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Cargo'),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tarifario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_tarifario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_tarifario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='remplazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Tarifario'),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.UnidadProduccion'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Empleado'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_cuenta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='unidades_produccion',
            field=models.ManyToManyField(to='recursos_h.UnidadProduccion'),
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together=set([('banco', 'numero')]),
        ),
    ]
