# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0002_auto_20170620_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='horas_trabajo',
            field=models.IntegerField(default=8, verbose_name='Horas de trabajo'),
        ),
    ]
