# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0003_contrato_horas_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocontrato',
            name='extra_diurna',
        ),
        migrations.RemoveField(
            model_name='tipocontrato',
            name='extra_dominical',
        ),
        migrations.RemoveField(
            model_name='tipocontrato',
            name='extra_dominical_nocturna',
        ),
        migrations.RemoveField(
            model_name='tipocontrato',
            name='extra_nocturna',
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='modalidad',
            field=models.IntegerField(choices=[(1, 'Por hora'), (2, 'Salario fijo')], default=1),
            preserve_default=False,
        ),
    ]
