# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0004_auto_20170629_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='valor_hora_diurna',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='valor_hora_nocturna',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
