# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0005_auto_20170630_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='valor_hora_festivo',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
