# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0006_cargo_valor_hora_festivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='horas_trabajo_corte',
            field=models.IntegerField(default=160, verbose_name='Horas de trabajo por corte'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='horas_trabajo_semanal',
            field=models.IntegerField(default=40, verbose_name='Horas de trabajo semanal'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='horas_trabajo',
            field=models.IntegerField(default=8, verbose_name='Horas de trabajo diarias'),
        ),
    ]
