# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0007_auto_20170701_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='subsidio_transporte',
            field=models.FloatField(default=0, verbose_name='Subcidio de transporte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='salario_base',
            field=models.FloatField(verbose_name='Salario base legal'),
        ),
    ]
