# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0008_auto_20170704_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='subsidio_transporte',
            field=models.FloatField(verbose_name='Subsidio de transporte'),
        ),
    ]
