# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0009_auto_20170704_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='subsidio_transporte',
            field=models.FloatField(default=0, verbose_name='Subsidio de transporte'),
        ),
    ]
