# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0009_auto_20170704_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='horas_trabajo_corte',
            field=models.IntegerField(default=160, verbose_name='Horas de trabajo mes'),
        ),
    ]
