# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0010_auto_20170706_0548'),
        ('recursos_h', '0010_auto_20170706_0816'),
    ]

    operations = [
    ]
