# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0011_merge_20170706_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='valor_hora_diurna',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='valor_hora_festivo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='valor_hora_nocturna',
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='modalidad',
            field=models.IntegerField(choices=[(1, 'Por hora'), (2, 'Salario fijo'), (3, 'Producci\xf3n')]),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Cargo'),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.UnidadProduccion'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='unidades_produccion',
            field=models.ManyToManyField(to='recursos_h.UnidadProduccion'),
        ),
    ]
