# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:01
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_h', '0013_auto_20170707_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifario',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tarifario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_tarifario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_tarifario', to=settings.AUTH_USER_MODEL),
        ),
    ]
