# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0014_auto_20170707_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifario',
            name='remplazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Tarifario'),
        ),
    ]
