# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0012_auto_20170707_2225'),
        ('recursos_h', '0015_tarifario_remplazado_por'),
    ]

    operations = [
    ]
