# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0016_merge_20170708_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.CharField(default='ypicoleal@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
