# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0016_merge_20170708_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
    ]
