# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0017_auto_20170708_2331'),
        ('recursos_h', '0017_auto_20170708_1736'),
    ]

    operations = [
    ]
