# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0018_merge_20170710_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario base legal'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='subsidio_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subsidio de transporte'),
        ),
        migrations.AlterField(
            model_name='tarifario',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
