# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0018_merge_20170710_1848'),
        ('recursos_h', '0019_auto_20170710_2258'),
    ]

    operations = [
    ]
