# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0020_merge_20170711_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='banco',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Banco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
