# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0021_auto_20170711_1956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='eliminado_por',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='last_editor',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero',
            field=models.CharField(max_length=100, verbose_name='Numero de cuenta'),
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
