# [START django_app]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT nominax.wsgi
threadsafe: yes


beta_settings:
    cloud_sql_instances: vertical-airway-172321:us-east1:ingecol-db

runtime_config:
  python_version: 2

# Google App Engine limits application deployments to 10,000 uploaded files per
# version. The skip_files section allows us to skip virtual environment files
# to meet this requirement. The first 5 are the default regular expressions to
# skip, while the last one is for all env/ files.
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$
