# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_h', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('entrada', models.TimeField()),
                ('salida', models.TimeField()),
                ('extras', models.IntegerField(blank=True, null=True, verbose_name='Hora extra')),
                ('extra_nocturna', models.IntegerField(blank=True, null=True, verbose_name='Hora extra nocturna')),
                ('extra_diurna', models.IntegerField(blank=True, null=True, verbose_name='Hora extra dierna')),
                ('extra_dominical', models.IntegerField(blank=True, null=True, verbose_name='Hora extra dominical')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Empleado')),
            ],
        ),
    ]
