# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='turno',
            name='descontar_almuerzo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turno.Concepto'),
        ),
    ]
