# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turno', '0002_auto_20170621_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='aprobado_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que aprobo el turno'),
        ),
    ]
