# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_auto_20170714_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turno.Concepto'),
        ),
    ]
