# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turno', '0003_auto_20170714_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_turno', to=settings.AUTH_USER_MODEL),
        ),
    ]
