# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0004_auto_20170715_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
