# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0004_auto_20170622_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='salida',
        ),
    ]
