# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0005_auto_20170622_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='entrada',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 22, 23, 4, 48, 352993)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='salida',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 22, 23, 4, 57, 713289)),
            preserve_default=False,
        ),
    ]
