# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0006_auto_20170622_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
