# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0007_turno_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
    ]
