# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0008_remove_turno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='extra_diurna',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora extra diurna'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='extra_dominical',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora extra dominical'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='extra_nocturna',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora extra nocturna'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='extras',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora extra'),
        ),
    ]
