# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0009_auto_20170623_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDominical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 'Domingo'), (2, 'Lunes'), (3, 'Martes'), (4, 'Mi\xe9rcoles'), (5, 'Jueves'), (6, 'Viernes'), (7, 'S\xe1bado')], verbose_name='D\xeda')),
            ],
        ),
        migrations.CreateModel(
            name='DiaFestivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(verbose_name='D\xeda')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
            ],
        ),
    ]
