# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0010_diadominical_diafestivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoFecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='turno',
            name='extra_diurna',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='extra_dominical',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='extra_nocturna',
        ),
        migrations.AlterField(
            model_name='diadominical',
            name='dia',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Mi\xe9rcoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'S\xe1bado'), (6, 'Domingo')], verbose_name='D\xeda'),
        ),
        migrations.RemoveField(
            model_name='turno',
            name='extras',
        ),
        migrations.AddField(
            model_name='turno',
            name='diurna',
            field=models.ManyToManyField(related_name='diurna', to='turno.RangoFecha'),
        ),
        migrations.AddField(
            model_name='turno',
            name='dominical',
            field=models.ManyToManyField(related_name='dominical', to='turno.RangoFecha'),
        ),
        migrations.AddField(
            model_name='turno',
            name='nocturna',
            field=models.ManyToManyField(related_name='nocturna', to='turno.RangoFecha'),
        ),
        migrations.AddField(
            model_name='turno',
            name='extras',
            field=models.ManyToManyField(related_name='extras', to='turno.RangoFecha'),
        ),
    ]
