# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0012_auto_20170629_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='diurna',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='dominical',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='nocturna',
        ),
    ]
