# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0013_auto_20170629_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='diurna',
            field=models.ManyToManyField(blank=True, related_name='diurna', to='turno.RangoFecha'),
        ),
        migrations.AddField(
            model_name='turno',
            name='dominical',
            field=models.ManyToManyField(blank=True, related_name='dominical', to='turno.RangoFecha'),
        ),
        migrations.AddField(
            model_name='turno',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='extras', to='turno.RangoFecha'),
        ),
        migrations.AddField(
            model_name='turno',
            name='nocturna',
            field=models.ManyToManyField(blank=True, related_name='nocturna', to='turno.RangoFecha'),
        ),
    ]
