# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0014_auto_20170629_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
