# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:24
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_h', '0012_auto_20170707_1824'),
        ('turno', '0015_auto_20170630_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_produccion', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_produccion', to=settings.AUTH_USER_MODEL)),
                ('empleados', models.ManyToManyField(to='recursos_h.Empleado')),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_produccion', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.UnidadProduccion')),
            ],
        ),
    ]
