# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_h', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_de_adelanto', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('nocturna', models.IntegerField(blank=True, verbose_name='Valor de recargo nocturno %')),
                ('dominical', models.IntegerField(blank=True, verbose_name='Valor de recargo dominical o festivo %')),
                ('nocturna_dominical', models.IntegerField(blank=True, verbose_name='Valor de recargo nocturno dominical o festivo %')),
                ('descuento_salud', models.IntegerField(blank=True, verbose_name='Descuento de salud y pensi\xf3n para empleado %')),
                ('prestaciones_sociales', models.IntegerField(blank=True, verbose_name='Pago de salud y pensi\xf3n del empleador %')),
                ('extra_diurna', models.IntegerField(blank=True, verbose_name='Valor de recargo de hora extra diurna %')),
                ('extra_nocturna', models.IntegerField(blank=True, verbose_name='Valor de recargo de hora extra nocturna %')),
                ('extra_dominical_diurna', models.IntegerField(blank=True, verbose_name='Valor de recargo de hora extra dominical %')),
                ('extra_dominical_nocturna', models.IntegerField(blank=True, verbose_name='Valor de recargo de hora extra dominical nocturna %')),
                ('tarifario', models.ManyToManyField(blank=True, to='recursos_h.Tarifario')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('contratos', models.ManyToManyField(to='recursos_h.Contrato')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.Corte')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_mes', models.DateField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('diurnas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora diurna')),
                ('nocturna', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora nocturna')),
                ('dominical_diurna', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora dominical diurna')),
                ('dominical_nocturna', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora dominical nocturna')),
                ('extras', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra diurna')),
                ('extra_nocturna', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra nocturna')),
                ('extra_dominical_diurna', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra dominical diurna')),
                ('extra_dominical_nocturna', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra dominical nocturna')),
                ('contrato', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Contrato')),
                ('corte', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Corte')),
            ],
        ),
    ]
