# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0002_auto_20170711_0341'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='fecha_de_adelanto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corte',
            name='tarifario',
            field=models.ManyToManyField(to='recursos_h.Tarifario'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='contrato',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Contrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomina',
            name='diurnas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='dominical_diurna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora dominical diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='dominical_nocturna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora dominical nocturna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extra_dominical_diurna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra dominical diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extra_dominical_nocturna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra dominical nocturna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extra_nocturna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra nocturna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nocturna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora nocturna'),
        ),
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='salario_base',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='subsidio_trasporte',
        ),
    ]
