# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='nomina',
            name='corte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nomina.Corte'),
            preserve_default=False,
        ),
    ]
