# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_auto_20170622_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corte',
            old_name='fecha_finalizacion',
            new_name='fecha_fin',
        ),
    ]
