# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0001_initial'),
        ('nomina', '0003_remove_corte_prestaciones_sociales'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('concepto', models.CharField(max_length=120)),
                ('corte', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Corte')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.UnidadProduccion')),
            ],
        ),
        migrations.CreateModel(
            name='DiaIncapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dias', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='descuento',
            name='recurrente',
            field=models.BooleanField(default=False),
        ),
    ]
