# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomina', '0004_auto_20170719_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentoproduccion',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='descuentoproduccion',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_descuentop', to=settings.AUTH_USER_MODEL),
        ),
    ]
