# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_auto_20170630_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='extra_diurna',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='extra_dominical',
        ),
        migrations.AddField(
            model_name='nomina',
            name='dominical_diurna',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hora dominical diurna'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='dominical_nocturna',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hora dominical nocturna'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='extra_dominical_diurna',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hora extra dominical diurna'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='extra_dominical_nocturna',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hora extra dominical nocturna'),
        ),
    ]
