# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_auto_20170701_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='dominical_diurna',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora dominical diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='dominical_nocturna',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora dominical nocturna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extra_dominical_diurna',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora extra dominical diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extra_dominical_nocturna',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora extra dominical nocturna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extra_nocturna',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora extra nocturna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extras',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora extra'),
        ),
    ]
