# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_auto_20170701_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='dominical',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo dominical o festivo %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corte',
            name='extra_diurna',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo de hora extra diurna %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corte',
            name='extra_dominical_diurna',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo de hora extra dominical %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corte',
            name='extra_dominical_nocturna',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo de hora extra dominical nocturna %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corte',
            name='extra_nocturna',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo de hora extra nocturna %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corte',
            name='nocturna',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo nocturno %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corte',
            name='nocturna_dominical',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo nocturno dominical o festivo %'),
            preserve_default=False,
        ),
    ]
