# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_descuento_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoIncapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(verbose_name='D\xeda desde el cual aplica')),
                ('porcentaje', models.IntegerField(verbose_name='Porcentaje a aplicar')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='pagoincapacidad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.TipoIncapacidad'),
        ),
        migrations.AddField(
            model_name='diaincapacidad',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nomina.TipoIncapacidad'),
            preserve_default=False,
        ),
    ]
