# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_auto_20170701_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='nocturna',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora nocturna'),
        ),
    ]
