# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_auto_20170720_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='corte_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corte_final', to='nomina.Corte'),
        ),
    ]
