# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_nomina_nocturna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='salario_base',
            field=models.FloatField(max_length=100),
        ),
    ]
