# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0001_initial'),
        ('nomina', '0009_auto_20170726_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentoproduccion',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Cargo'),
            preserve_default=False,
        ),
    ]
