# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0010_auto_20170703_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='diurnas',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora diurna'),
        ),
    ]
