# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0011_nomina_diurnas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='extras',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora extra diurna'),
        ),
    ]
