# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0012_auto_20170704_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='subsidio_trasporte',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
