# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0013_auto_20170704_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='bonificacion',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='prestaciones_sociales',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salario_produccion',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
