# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0014_auto_20170704_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='bonificacion',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='prestaciones_sociales',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='salario_produccion',
        ),
        migrations.AddField(
            model_name='corte',
            name='descuento_salud',
            field=models.IntegerField(default=8, verbose_name='Descuento de salud y pensi\xf3n para empleado %'),
            preserve_default=False,
        ),
    ]
