# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0015_auto_20170704_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='prestaciones_sociales',
            field=models.IntegerField(default=46, verbose_name='Pago de salud y pensi\xf3n del empleador %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_diurna',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_dominicales',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_nocturna',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
