# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0016_auto_20170704_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='inicio_mes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
