# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0017_nomina_inicio_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
