# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0018_auto_20170706_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='horas_diurna',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='horas_dominicales',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='horas_nocturna',
        ),
    ]
