# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0018_merge_20170710_1919'),
        ('nomina', '0020_corte_tarifario'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='fecha_de_adelanto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Contrato'),
            preserve_default=False,
        ),
    ]
