# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0021_auto_20170710_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='salario_base',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='subsidio_trasporte',
        ),
        migrations.AlterField(
            model_name='nomina',
            name='contrato',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Contrato'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='diurnas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='dominical_diurna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora dominical diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='dominical_nocturna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora dominical nocturna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extra_dominical_diurna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra dominical diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extra_dominical_nocturna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra dominical nocturna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extra_nocturna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra nocturna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='extras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora extra diurna'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='nocturna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hora nocturna'),
        ),
    ]
