# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0020_merge_20170711_0019'),
        ('nomina', '0022_auto_20170710_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='empleado',
        ),
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together=set([('contrato', 'corte')]),
        ),
    ]
