# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0020_merge_20170711_0019'),
        ('nomina', '0023_auto_20170711_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recursos_h.Empleado'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together=set([('empleado', 'corte')]),
        ),
    ]
