# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0026_auto_20170711_0022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together=set([]),
        ),
    ]
