# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0022_auto_20170712_1849'),
        ('nomina', '0028_remove_nomina_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad $')),
                ('contratos', models.ManyToManyField(to='recursos_h.Contrato')),
            ],
        ),
        migrations.AlterField(
            model_name='corte',
            name='descuento_salud',
            field=models.IntegerField(blank=True, verbose_name='Descuento de salud y pensi\xf3n para empleado %'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='dominical',
            field=models.IntegerField(blank=True, verbose_name='Valor de recargo dominical o festivo %'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='extra_diurna',
            field=models.IntegerField(blank=True, verbose_name='Valor de recargo de hora extra diurna %'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='extra_dominical_diurna',
            field=models.IntegerField(blank=True, verbose_name='Valor de recargo de hora extra dominical %'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='extra_dominical_nocturna',
            field=models.IntegerField(blank=True, verbose_name='Valor de recargo de hora extra dominical nocturna %'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='extra_nocturna',
            field=models.IntegerField(blank=True, verbose_name='Valor de recargo de hora extra nocturna %'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='nocturna',
            field=models.IntegerField(blank=True, verbose_name='Valor de recargo nocturno %'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='nocturna_dominical',
            field=models.IntegerField(blank=True, verbose_name='Valor de recargo nocturno dominical o festivo %'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='prestaciones_sociales',
            field=models.IntegerField(blank=True, verbose_name='Pago de salud y pensi\xf3n del empleador %'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='tarifario',
            field=models.ManyToManyField(blank=True, to='recursos_h.Tarifario'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='corte',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Corte'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='corte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.Corte'),
        ),
    ]
