# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomina', '0029_auto_20170712_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='descuento',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_descuento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='corte',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nomina.Corte'),
        ),
    ]
