# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:03
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_corte', models.IntegerField(choices=[(0, 'Quincenal'), (1, 'Mensual')])),
                ('primer_dia', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31)], verbose_name='Primer dia de corte')),
                ('segundo_dia', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)], verbose_name='Segundo dia de corte')),
                ('h_recargo_nocturno', models.TimeField()),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_configuracion', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configucari\xf3n',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
