# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 21:09
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_h', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('referencia', models.IntegerField(choices=[(1, 'Extras'), (2, 'Extra nocturna'), (3, 'Extra diurna'), (4, 'Extra dominical')])),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_corte', models.IntegerField(choices=[(0, 'Quincenal'), (1, 'Mensual')])),
                ('primer_dia', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31)], verbose_name='Primer dia de corte')),
                ('segundo_dia', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)], verbose_name='Segundo dia de corte')),
                ('nit', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('S', 'Ahorros'), ('D', 'Corriente')], max_length=2)),
                ('h_recargo_nocturno_inicio', models.TimeField(verbose_name='Hora de inicio de recargo nocturno')),
                ('h_recargo_nocturno_fin', models.TimeField(verbose_name='Hora de finalizaci\xf3n de recargo nocturno')),
                ('h_almuerzo_inicio', models.TimeField(verbose_name='Hora de inicio de almuerzo')),
                ('h_almuerzo_fin', models.TimeField(verbose_name='Hora de fin de almuerzo')),
                ('descuento_salud', models.IntegerField(verbose_name='Descuento de salud y pensi\xf3n para empleado %')),
                ('prestaciones_sociales', models.IntegerField(verbose_name='Pago de salud y pensi\xf3n del empleador %')),
                ('nocturna', models.IntegerField(verbose_name='Valor de recargo nocturno %')),
                ('dominical', models.IntegerField(verbose_name='Valor de recargo dominical o festivo %')),
                ('nocturna_dominical', models.IntegerField(verbose_name='Valor de recargo nocturno dominical o festivo %')),
                ('extra_diurna', models.IntegerField(verbose_name='Valor de recargo de hora extra diurna %')),
                ('extra_nocturna', models.IntegerField(verbose_name='Valor de recargo de hora extra nocturna %')),
                ('extra_dominical_diurna', models.IntegerField(verbose_name='Valor de recargo de hora extra dominical %')),
                ('extra_dominical_nocturna', models.IntegerField(verbose_name='Valor de recargo de hora extra dominical nocturna %')),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_configuracion', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_configuracion', to=settings.AUTH_USER_MODEL)),
                ('tarifario', models.ManyToManyField(to='recursos_h.Tarifario')),
            ],
            options={
                'verbose_name': 'Configucari\xf3n',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
