# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('referencia', models.IntegerField(choices=[(1, 'Extras'), (2, 'Extra nocturna'), (3, 'Extra diurna'), (4, 'Extra dominical')])),
            ],
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='h_recargo_nocturno',
            field=models.TimeField(verbose_name='Hora de recargo nocturno'),
        ),
    ]
