# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_remove_configuracion_prestaciones_sociales'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='h_descanso_fin',
            field=models.TimeField(default='13:00', verbose_name='Hora de fin de descanso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='h_descanso_inicio',
            field=models.TimeField(default='14:00', verbose_name='Hora de inicio de descanso'),
            preserve_default=False,
        ),
    ]
