# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20170622_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='h_recargo_nocturno',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='h_recargo_nocturno_fin',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora final de recargo nocturno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='h_recargo_nocturno_inicio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de inicio de recargo nocturno'),
            preserve_default=False,
        ),
    ]
