# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20170622_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='h_recargo_nocturno_fin',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='h_recargo_hora_extra',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora inicio de recargo de hora extra'),
            preserve_default=False,
        ),
    ]
