# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20170718_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='h_descanso_fin',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='h_descanso_inicio',
        ),
    ]
