# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20170623_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='h_recargo_hora_extra',
        ),
    ]
