# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20170718_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoIncapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(verbose_name='D\xeda desde el cual aplica')),
                ('porcentaje', models.IntegerField(verbose_name='Porcentaje a aplicar')),
            ],
        ),
    ]
