# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_remove_configuracion_h_recargo_hora_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='h_recargo_nocturno_fin',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de fin de recargo nocturno'),
            preserve_default=False,
        ),
    ]
