# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_configuracion_h_recargo_nocturno_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='h_almuerzo_fin',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de fin de almuerzo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='h_almuerzo_inicio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de inicio de almuerzo'),
            preserve_default=False,
        ),
    ]
