# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_delete_pagoincapacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='salario_minimo_dia',
            field=models.IntegerField(default=24000, verbose_name='Dia de salario m\xednimo'),
            preserve_default=False,
        ),
    ]
