# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_auto_20170629_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='h_recargo_nocturno_fin',
            field=models.TimeField(verbose_name='Hora de finalizaci\xf3n de recargo nocturno'),
        ),
    ]
