# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_auto_20170630_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='dominical',
            field=models.IntegerField(verbose_name='Valor de recargo dominical o festivo %'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='extra_diurna',
            field=models.IntegerField(verbose_name='Valor de recargo de hora extra diurna %'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='extra_dominical_diurna',
            field=models.IntegerField(verbose_name='Valor de recargo de hora extra dominical %'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='extra_dominical_nocturna',
            field=models.IntegerField(verbose_name='Valor de recargo de hora extra dominical nocturna %'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='extra_nocturna',
            field=models.IntegerField(verbose_name='Valor de recargo de hora extra nocturna %'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nocturna',
            field=models.IntegerField(verbose_name='Valor de recargo nocturno %'),
        ),
    ]
