# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_auto_20170701_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='nocturna_dominical',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo nocturno dominical o festivo %'),
            preserve_default=False,
        ),
    ]
