# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_configuracion_nocturna_dominical'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='descuento_salud',
            field=models.IntegerField(default=8, verbose_name='Descuento de salud y pensi\xf3n para empleado %'),
            preserve_default=False,
        ),
    ]
