# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0013_configuracion_descuento_salud'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='prestaciones_sociales',
            field=models.IntegerField(default=46, verbose_name='Pago de salud y pensi\xf3n del empleador %'),
            preserve_default=False,
        ),
    ]
