# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_h', '0012_auto_20170707_1824'),
        ('configuracion', '0014_configuracion_prestaciones_sociales'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tarifario',
            field=models.ManyToManyField(to='recursos_h.Tarifario'),
        ),
    ]
