# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0015_configuracion_tarifario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='nit',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
