# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0016_configuracion_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='numero_cuenta',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tipo_cuenta',
            field=models.CharField(choices=[('S', 'Ahorros'), ('D', 'Corriente')], default='S', max_length=2),
            preserve_default=False,
        ),
    ]
