# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 17:17
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identificacion', models.CharField(max_length=120, unique=True, verbose_name='Identificaci\xf3n')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel\xe9fono')),
                ('fijo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fijo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identificacion', models.CharField(max_length=120, unique=True, verbose_name='Identificaci\xf3n')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel\xe9fono')),
                ('fijo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fijo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('eliminado', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asistente', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_asistente', to=settings.AUTH_USER_MODEL)),
                ('last_editor', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_asistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='creator',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_administrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrador',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminado_por_administrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrador',
            name='last_editor',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_administrador', to=settings.AUTH_USER_MODEL),
        ),
    ]
