# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administador',
            new_name='Administrador',
        ),
    ]
